import { Schema, model, models } from 'mongoose';

const location = new Schema({ city: String, locality: String, latitude: Number, longitude: Number }, { _id: false });
const milestones = new Schema({ label: String, status: { type: String, default: 'pending' }, completedAt: Date }, { _id: false });
const UserSchema = new Schema({
  name: { type: String, required: true, trim: true }, email: { type: String, required: true, trim: true, lowercase: true, unique: true, index: true }, phone: { type: String, index: true }, passwordHash: { type: String, required: true, select: false }, role: { type: String, enum: ['student', 'business'], required: true, index: true }, profilePhoto: String,
  isVerified: { type: Boolean, default: false }, verificationStatus: { type: String, enum: ['pending', 'verified', 'requires_action', 'rejected'], default: 'pending' }, verificationSubmittedAt: Date, location, skills: { type: [String], default: [] }, availability: { type: [String], default: [] }, preferredWorkRadius: { type: Number, default: 10 }, rating: { type: Number, default: 0 }, reviewCount: { type: Number, default: 0 }, completedGigs: { type: Number, default: 0 },
  college: String, course: String, year: String, studentId: String, portfolio: { type: [Schema.Types.Mixed], default: [] }, earnings: { type: Number, default: 0 }, businessName: String, businessCategory: String, businessDescription: String, businessAddress: String,
}, { timestamps: true, toJSON: { transform: (_d, r: any) => { r.passwordHash = undefined; return r; } } });
const GigSchema = new Schema({ businessId: { type: Schema.Types.ObjectId, ref: 'User', required: true, index: true }, title: { type: String, required: true, trim: true }, description: { type: String, required: true }, category: { type: String, required: true, index: true }, requiredSkills: { type: [String], default: [], index: true }, budget: { type: Number, required: true, min: 0 }, duration: String, workType: { type: String, enum: ['remote', 'on-site', 'both'], default: 'both' }, location, preferredRadius: Number, startDate: Date, deadline: Date, deliverables: { type: [String], default: [] }, status: { type: String, enum: ['draft', 'active', 'paused', 'assigned', 'in_progress', 'submitted', 'completed', 'cancelled'], default: 'draft', index: true }, applicationCount: { type: Number, default: 0 }, selectedStudentId: { type: Schema.Types.ObjectId, ref: 'User' } }, { timestamps: true });
const ApplicationSchema = new Schema({ gigId: { type: Schema.Types.ObjectId, ref: 'Gig', required: true, index: true }, studentId: { type: Schema.Types.ObjectId, ref: 'User', required: true, index: true }, proposal: { type: String, required: true }, experience: String, availability: String, estimatedCompletionTime: String, portfolioLinks: { type: [String], default: [] }, status: { type: String, enum: ['pending', 'shortlisted', 'selected', 'rejected', 'withdrawn', 'completed'], default: 'pending', index: true } }, { timestamps: true }); ApplicationSchema.index({ gigId: 1, studentId: 1 }, { unique: true });
const EngagementSchema = new Schema({ gigId: { type: Schema.Types.ObjectId, ref: 'Gig', required: true, index: true }, businessId: { type: Schema.Types.ObjectId, ref: 'User', required: true, index: true }, studentId: { type: Schema.Types.ObjectId, ref: 'User', required: true, index: true }, status: { type: String, enum: ['assigned', 'work_started', 'submitted', 'under_review', 'revision_requested', 'approved', 'completed', 'paid'], default: 'assigned', index: true }, milestones: { type: [milestones], default: [] }, currentMilestone: String, startedAt: Date, submittedAt: Date, completedAt: Date, deadline: Date }, { timestamps: true });
const DeliverableSchema = new Schema({ engagementId: { type: Schema.Types.ObjectId, ref: 'Engagement', required: true, index: true }, submittedBy: { type: Schema.Types.ObjectId, ref: 'User', required: true }, version: { type: Number, required: true }, message: String, files: { type: [Schema.Types.Mixed], default: [] }, links: { type: [String], default: [] }, status: { type: String, enum: ['submitted', 'under_review', 'revision_requested', 'approved'], default: 'submitted' }, feedback: String }, { timestamps: true });
const ReviewSchema = new Schema({ gigId: { type: Schema.Types.ObjectId, ref: 'Gig', required: true }, engagementId: { type: Schema.Types.ObjectId, ref: 'Engagement', required: true }, reviewerId: { type: Schema.Types.ObjectId, ref: 'User', required: true }, revieweeId: { type: Schema.Types.ObjectId, ref: 'User', required: true }, rating: { type: Number, min: 1, max: 5, required: true }, tags: { type: [String], default: [] }, comment: String }, { timestamps: true }); ReviewSchema.index({ engagementId: 1, reviewerId: 1 }, { unique: true });
const ConversationSchema = new Schema({ participants: { type: [Schema.Types.ObjectId], ref: 'User', required: true }, gigId: { type: Schema.Types.ObjectId, ref: 'Gig' }, engagementId: { type: Schema.Types.ObjectId, ref: 'Engagement' }, lastMessageAt: Date }, { timestamps: true });
const MessageSchema = new Schema({ conversationId: { type: Schema.Types.ObjectId, ref: 'Conversation', required: true, index: true }, senderId: { type: Schema.Types.ObjectId, ref: 'User', required: true }, text: { type: String, required: true, trim: true }, read: { type: Boolean, default: false } }, { timestamps: true }); MessageSchema.index({ conversationId: 1, createdAt: 1 });
const NotificationSchema = new Schema({ userId: { type: Schema.Types.ObjectId, ref: 'User', required: true, index: true }, type: { type: String, required: true }, title: String, message: String, read: { type: Boolean, default: false, index: true }, relatedId: Schema.Types.ObjectId }, { timestamps: true });
const TransactionSchema = new Schema({ gigId: { type: Schema.Types.ObjectId, ref: 'Gig', required: true }, engagementId: { type: Schema.Types.ObjectId, ref: 'Engagement', required: true, unique: true }, businessId: { type: Schema.Types.ObjectId, ref: 'User', required: true }, studentId: { type: Schema.Types.ObjectId, ref: 'User', required: true }, amount: Number, platformFee: Number, gst: Number, total: Number, status: { type: String, enum: ['pending', 'authorized', 'released', 'completed', 'failed'], default: 'pending' }, transactionId: String }, { timestamps: true });
const SavedGigSchema = new Schema({ userId: { type: Schema.Types.ObjectId, ref: 'User', required: true }, gigId: { type: Schema.Types.ObjectId, ref: 'Gig', required: true } }, { timestamps: true }); SavedGigSchema.index({ userId: 1, gigId: 1 }, { unique: true });
const SavedTalentSchema = new Schema({ businessId: { type: Schema.Types.ObjectId, ref: 'User', required: true }, studentId: { type: Schema.Types.ObjectId, ref: 'User', required: true } }, { timestamps: true }); SavedTalentSchema.index({ businessId: 1, studentId: 1 }, { unique: true });
const SupportTicketSchema = new Schema({ userId: { type: Schema.Types.ObjectId, ref: 'User', required: true }, category: { type: String, enum: ['report_user', 'payment_issue', 'verification', 'work_dispute', 'technical', 'other'], required: true }, reason: String, description: { type: String, required: true }, attachments: { type: [Schema.Types.Mixed], default: [] }, status: { type: String, default: 'open' } }, { timestamps: true });
const get = (name: string, schema: Schema): any => (models[name] as any) || model(name, schema);
export const User = get('User', UserSchema); export const Gig = get('Gig', GigSchema); export const Application = get('Application', ApplicationSchema); export const Engagement = get('Engagement', EngagementSchema); export const Deliverable = get('Deliverable', DeliverableSchema); export const Review = get('Review', ReviewSchema); export const Conversation = get('Conversation', ConversationSchema); export const Message = get('Message', MessageSchema); export const Notification = get('Notification', NotificationSchema); export const Transaction = get('Transaction', TransactionSchema); export const SavedGig = get('SavedGig', SavedGigSchema); export const SavedTalent = get('SavedTalent', SavedTalentSchema); export const SupportTicket = get('SupportTicket', SupportTicketSchema);
