import { Candidate } from '../types';

export const mockCandidates: Candidate[] = [
  {
    id: 'CAN-001',
    name: 'Arjun Mehta',
    initials: 'AM',
    avatarColor: '#6366F1',
    college: 'IIT Bombay',
    degree: 'B.Tech',
    year: '3rd Year',
    skills: ['Graphic Design', 'UI/UX Design', 'Photography', 'Figma'],
    rating: 4.9,
    gigsCompleted: 12,
    matchPercentage: 98,
    distance: '2.1 km',
    isVerified: true,
    availability: 'Immediate',
    portfolio: [
      {
        id: 'PORT-001',
        category: 'BRAND IDENTITY',
        title: 'Cafe Branding Package',
        subtitle: 'Modern Bites Cafe',
        rating: 4.9,
        date: 'Oct 2025',
        price: 4500,
      },
      {
        id: 'PORT-002',
        category: 'SOCIAL MEDIA',
        title: 'Instagram Growth Campaign',
        subtitle: 'FitZone Gym',
        rating: 4.8,
        date: 'Sep 2025',
        price: 3500,
      },
      {
        id: 'PORT-003',
        category: 'UI/UX DESIGN',
        title: 'E-commerce App Redesign',
        subtitle: 'ShopLocal India',
        rating: 5.0,
        date: 'Aug 2025',
        price: 8000,
      },
    ],
    reviews: [
      {
        id: 'REV-001',
        reviewerName: 'Modern Bites Cafe',
        reviewerInitials: 'MB',
        reviewerAvatarColor: '#2563EB',
        isVerified: true,
        reviewerLabel: 'Verified MSME',
        gigTitle: 'Cafe Branding Package',
        completionDate: 'Oct 15, 2025',
        rating: 5,
        text: 'Arjun delivered exceptional branding work. His attention to detail and understanding of our brand vision was impressive. Highly recommended for any design work.',
        price: 4500,
      },
    ],
  },
  {
    id: 'CAN-002',
    name: 'Sneha Kapoor',
    initials: 'SK',
    avatarColor: '#10B981',
    college: "St. Xavier's College",
    degree: 'B.Com',
    year: '2nd Year',
    skills: ['Content Writing', 'Social Media', 'Marketing', 'SEO'],
    rating: 4.8,
    gigsCompleted: 8,
    matchPercentage: 92,
    distance: '3.5 km',
    isVerified: true,
    availability: 'Part-time',
    portfolio: [
      {
        id: 'PORT-004',
        category: 'CONTENT WRITING',
        title: 'Blog Content Strategy',
        subtitle: 'TechStart Solutions',
        rating: 4.8,
        date: 'Sep 2025',
        price: 3000,
      },
    ],
    reviews: [
      {
        id: 'REV-002',
        reviewerName: 'TechStart Solutions',
        reviewerInitials: 'TS',
        reviewerAvatarColor: '#2563EB',
        isVerified: true,
        reviewerLabel: 'Verified Business',
        gigTitle: 'Blog Content Strategy',
        completionDate: 'Sep 20, 2025',
        rating: 5,
        text: 'Sneha is an excellent content writer. She understood our tech audience perfectly and delivered engaging, well-researched blog posts.',
      },
    ],
  },
  {
    id: 'CAN-003',
    name: 'Rohan Das',
    initials: 'RD',
    avatarColor: '#F59E0B',
    college: 'NMIMS University',
    degree: 'BBA',
    year: '3rd Year',
    skills: ['Video Editing', 'Photography', 'Social Media', 'Adobe Premiere'],
    rating: 4.7,
    gigsCompleted: 5,
    matchPercentage: 85,
    distance: '4.8 km',
    isVerified: true,
    availability: 'Weekends',
    portfolio: [
      {
        id: 'PORT-005',
        category: 'VIDEO PRODUCTION',
        title: 'Product Launch Video',
        subtitle: 'Retail Hub',
        rating: 4.7,
        date: 'Oct 2025',
        price: 5000,
      },
    ],
    reviews: [],
  },
  {
    id: 'CAN-004',
    name: 'Priya Sharma',
    initials: 'PS',
    avatarColor: '#EF4444',
    college: 'HR College of Commerce',
    degree: 'B.Com',
    year: '2nd Year',
    skills: ['Data Entry', 'Excel', 'Social Media', 'Marketing'],
    rating: 4.9,
    gigsCompleted: 15,
    matchPercentage: 82,
    distance: '6.0 km',
    isVerified: true,
    availability: 'Immediate',
    portfolio: [
      {
        id: 'PORT-006',
        category: 'DATA MANAGEMENT',
        title: 'Inventory Digitization',
        subtitle: 'Local Mart',
        rating: 4.9,
        date: 'Oct 2025',
        price: 2000,
      },
    ],
    reviews: [
      {
        id: 'REV-003',
        reviewerName: 'Local Mart',
        reviewerInitials: 'LM',
        reviewerAvatarColor: '#10B981',
        isVerified: true,
        reviewerLabel: 'Verified MSME',
        gigTitle: 'Inventory Digitization',
        completionDate: 'Oct 5, 2025',
        rating: 5,
        text: 'Priya was incredibly thorough and accurate with our inventory data. She finished ahead of schedule and even suggested improvements to our categorization system.',
        price: 2000,
      },
    ],
  },
];
