import { Gig, Application } from '../types';

export const mockGigs: Gig[] = [
  {
    id: 'GIG-001',
    title: 'Create Instagram Content Pack',
    businessId: 'BIZ-002',
    businessName: 'Modern Bites Cafe',
    businessInitials: 'MB',
    businessAvatarColor: '#2563EB',
    isBusinessVerified: true,
    category: 'Design & Creative',
    description:
      'We need a talented designer to create a comprehensive Instagram content pack for our cafe. This includes 10 high-resolution posts featuring our new menu items, brand-consistent stories templates, and a cohesive visual style that reflects our modern, urban aesthetic. The content should be ready to post and optimized for Instagram engagement.',
    skills: ['Graphic Design', 'Social Media', 'Photography', 'Content Writing'],
    budget: 2500,
    duration: '3 days',
    deadline: '24 Oct',
    location: 'Powai, Mumbai',
    distance: '2.3 km',
    workType: 'on-site',
    status: 'open',
    applicantCount: 8,
    rating: 4.5,
    reviewCount: 12,
    deliverables: [
      'Initial 5 concept sketches',
      'Brand color palette & typography',
      'Final 10 high-res IG posts (PNG/MP4)',
    ],
    postedDate: '2 days ago',
    isSaved: false,
    matchPercentage: 92,
  },
  {
    id: 'GIG-002',
    title: 'Social Media Content Pack',
    businessId: 'BIZ-003',
    businessName: "Aman's Gourmet Cafe",
    businessInitials: 'AG',
    businessAvatarColor: '#10B981',
    isBusinessVerified: true,
    category: 'Marketing & Social',
    description:
      'Looking for a creative social media manager to curate and design a full month of social media content for our gourmet cafe. This includes posts for Instagram, Facebook, and WhatsApp Status.',
    skills: ['Social Media', 'Content Writing', 'Graphic Design'],
    budget: 4500,
    duration: '1 week',
    deadline: '28 Oct',
    location: 'Andheri East, Mumbai',
    distance: '4.1 km',
    workType: 'remote',
    status: 'open',
    applicantCount: 12,
    rating: 4.3,
    reviewCount: 8,
    deliverables: [
      '30 social media posts with captions',
      'Content calendar for the month',
      'Brand voice guidelines document',
      'Analytics report template',
    ],
    postedDate: '1 day ago',
    isSaved: true,
    matchPercentage: 88,
  },
  {
    id: 'GIG-003',
    title: 'Product Photography for New Catalog',
    businessId: 'BIZ-001',
    businessName: 'Retail Hub',
    businessInitials: 'RH',
    businessAvatarColor: '#6366F1',
    isBusinessVerified: true,
    category: 'Photography',
    description:
      'We are updating our product catalog and need professional product photography for 50+ items. The shoot will be at our store in Andheri East. Equipment will be provided if needed.',
    skills: ['Photography', 'Product Photography', 'Photo Editing'],
    budget: 5000,
    duration: '2 days',
    deadline: '24 Oct',
    location: 'Andheri East, Mumbai',
    distance: '5.2 km',
    workType: 'on-site',
    status: 'active',
    applicantCount: 12,
    rating: 4.7,
    reviewCount: 15,
    deliverables: [
      'High-res product photos (50+ items)',
      'Edited and color-corrected images',
      'White background versions',
    ],
    postedDate: '3 days ago',
    isSaved: false,
    matchPercentage: 85,
  },
  {
    id: 'GIG-004',
    title: 'Social Media Content Strategy',
    businessId: 'BIZ-004',
    businessName: 'FitZone Gym',
    businessInitials: 'FZ',
    businessAvatarColor: '#F59E0B',
    isBusinessVerified: true,
    category: 'Marketing & Social',
    description:
      'Develop a comprehensive social media strategy for our gym including content calendar, post templates, and engagement tactics for Instagram and Facebook.',
    skills: ['Social Media', 'Marketing', 'Content Writing'],
    budget: 3500,
    duration: '5 days',
    deadline: '28 Oct',
    location: 'Vile Parle, Mumbai',
    distance: '6.8 km',
    workType: 'remote',
    status: 'active',
    applicantCount: 8,
    rating: 4.2,
    reviewCount: 6,
    deliverables: [
      'Social media strategy document',
      '15 post templates',
      'Engagement playbook',
    ],
    postedDate: '4 days ago',
    isSaved: false,
    matchPercentage: 78,
  },
  {
    id: 'GIG-005',
    title: 'Data Entry for Inventory',
    businessId: 'BIZ-001',
    businessName: 'Retail Hub',
    businessInitials: 'RH',
    businessAvatarColor: '#6366F1',
    isBusinessVerified: true,
    category: 'Data & Admin',
    description:
      'We need help organizing and entering our inventory data into a new management system. Around 500 SKUs need to be cataloged with descriptions, prices, and categories.',
    skills: ['Data Entry', 'Excel', 'Administration'],
    budget: 1500,
    duration: '2 days',
    deadline: '02 Nov',
    location: 'Andheri East, Mumbai',
    distance: '5.2 km',
    workType: 'on-site',
    status: 'pending',
    applicantCount: 4,
    rating: 0,
    reviewCount: 0,
    deliverables: [
      'Complete inventory spreadsheet',
      'Category mapping document',
      'Data validation report',
    ],
    postedDate: '1 day ago',
    isSaved: false,
  },
  {
    id: 'GIG-006',
    title: 'Logo Design & Brand Identity',
    businessId: 'BIZ-005',
    businessName: 'Fresh Bakes Studio',
    businessInitials: 'FB',
    businessAvatarColor: '#EF4444',
    isBusinessVerified: true,
    category: 'Design & Creative',
    description:
      'We are a new artisan bakery and need a complete brand identity package including logo, color palette, typography, and basic brand guidelines.',
    skills: ['Graphic Design', 'Logo Design', 'Branding'],
    budget: 8000,
    duration: '1 week',
    deadline: '30 Oct',
    location: 'Powai, Mumbai',
    distance: '1.5 km',
    workType: 'remote',
    status: 'open',
    applicantCount: 15,
    rating: 4.8,
    reviewCount: 20,
    deliverables: [
      'Logo concepts (5 variations)',
      'Final logo files (SVG, PNG, PDF)',
      'Brand color palette',
      'Typography guide',
      'Brand guidelines PDF',
    ],
    postedDate: '5 hours ago',
    isSaved: true,
    matchPercentage: 95,
  },
  {
    id: 'GIG-007',
    title: 'Website Landing Page Design',
    businessId: 'BIZ-006',
    businessName: 'TechStart Solutions',
    businessInitials: 'TS',
    businessAvatarColor: '#2563EB',
    isBusinessVerified: true,
    category: 'Development & IT',
    description:
      'Design and develop a modern landing page for our SaaS product. Should be responsive, fast-loading, and conversion-optimized.',
    skills: ['Web Development', 'UI/UX Design', 'HTML/CSS'],
    budget: 6000,
    duration: '5 days',
    deadline: '01 Nov',
    location: 'Powai, Mumbai',
    distance: '3.0 km',
    workType: 'remote',
    status: 'open',
    applicantCount: 10,
    rating: 4.6,
    reviewCount: 18,
    deliverables: [
      'Figma mockup',
      'Responsive HTML/CSS/JS',
      'Performance optimization report',
    ],
    postedDate: '12 hours ago',
    isSaved: false,
    matchPercentage: 80,
  },
];

export const mockApplications: Application[] = [
  {
    id: 'APP-001',
    gigId: 'GIG-001',
    gigTitle: 'Create Instagram Content Pack',
    businessName: 'Modern Bites Cafe',
    businessInitials: 'MB',
    businessAvatarColor: '#2563EB',
    isBusinessVerified: true,
    status: 'active',
    appliedDate: '18 Oct 2025',
    duration: '3 days',
    budget: 2500,
    progress: 65,
  },
  {
    id: 'APP-002',
    gigId: 'GIG-002',
    gigTitle: 'Social Media Content Pack',
    businessName: "Aman's Gourmet Cafe",
    businessInitials: 'AG',
    businessAvatarColor: '#10B981',
    isBusinessVerified: true,
    status: 'shortlisted',
    appliedDate: '19 Oct 2025',
    duration: '1 week',
    budget: 4500,
  },
  {
    id: 'APP-003',
    gigId: 'GIG-006',
    gigTitle: 'Logo Design & Brand Identity',
    businessName: 'Fresh Bakes Studio',
    businessInitials: 'FB',
    businessAvatarColor: '#EF4444',
    isBusinessVerified: true,
    status: 'applied',
    appliedDate: '20 Oct 2025',
    duration: '1 week',
    budget: 8000,
  },
  {
    id: 'APP-004',
    gigId: 'GIG-003',
    gigTitle: 'Product Photography for New Catalog',
    businessName: 'Retail Hub',
    businessInitials: 'RH',
    businessAvatarColor: '#6366F1',
    isBusinessVerified: true,
    status: 'completed',
    appliedDate: '10 Oct 2025',
    duration: '2 days',
    budget: 5000,
    progress: 100,
  },
];
