import { StudentProfile, BusinessProfile } from '../types';

export const studentUser: StudentProfile = {
  id: 'STU-001',
  role: 'student',
  name: 'Sandesh Kumar',
  initials: 'SK',
  email: 'sandesh.kumar@iitb.ac.in',
  phone: '+91 98765 43210',
  avatarColor: '#2563EB',
  isVerified: true,
  location: 'Powai, Mumbai',
  joinedDate: 'March 2025',
  college: 'IIT Bombay',
  degree: 'B.Tech Computer Science',
  year: '3rd Year',
  skills: ['Graphic Design', 'Social Media', 'Content Writing', 'Video Editing', 'UI/UX Design', 'Photography'],
  rating: 4.9,
  gigsCompleted: 24,
  totalEarnings: 42850,
  pendingEarnings: 3200,
  monthlyEarnings: 12400,
  workRadius: 15,
  workPreference: 'on-site',
  availability: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
};

export const businessUser: BusinessProfile = {
  id: 'BIZ-001',
  role: 'business',
  name: 'Rajesh Patel',
  initials: 'RH',
  email: 'rajesh@retailhub.in',
  phone: '+91 98765 12345',
  avatarColor: '#6366F1',
  isVerified: true,
  location: 'Andheri East, Mumbai',
  joinedDate: 'January 2025',
  businessName: 'Retail Hub',
  gstin: '27AABCU9603R1ZM',
  category: 'Retail & Commerce',
  activeGigs: 3,
  totalApplicants: 24,
  activeWorkers: 2,
  totalSpend: 12400,
  memberSince: '2024',
};
