import React, { useMemo, useState } from 'react';
import { Alert, ScrollView, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useNavigation } from '@react-navigation/native';
import { CheckCircle2, ChevronLeft, FileCheck2, IndianRupee, MessageCircle, Plus, Search, ShieldCheck, Star, UserCheck } from 'lucide-react-native';
import { CandidateCard, GigCard, MilestoneStepper, StatusPill, SuccessState } from '../components';
import { mockCandidates } from '../mockData/candidates';
import { businessUser, studentUser } from '../mockData/user';
import { useDemo } from '../state/DemoContext';
import type { Gig } from '../types';

const Screen = ({ title, children }: { title: string; children: React.ReactNode }) => {
  const navigation = useNavigation<any>();
  return <SafeAreaView className="flex-1 bg-slate-50"><View className="px-5 py-3 flex-row items-center border-b border-slate-100 bg-white"><TouchableOpacity onPress={() => navigation.goBack()} className="mr-3"><ChevronLeft color="#0F172A" /></TouchableOpacity><Text className="text-lg font-bold text-slate-900">{title}</Text></View>{children}</SafeAreaView>;
};
const Cta = ({ label, onPress, secondary = false }: { label: string; onPress: () => void; secondary?: boolean }) => <TouchableOpacity onPress={onPress} className={`rounded-full py-3.5 items-center ${secondary ? 'border border-slate-200 bg-white' : 'bg-blue-600'}`}><Text className={`font-bold ${secondary ? 'text-slate-700' : 'text-white'}`}>{label}</Text></TouchableOpacity>;

export const MyGigsScreen = () => {
  const navigation = useNavigation<any>(); const { applications, workState } = useDemo();
  return <SafeAreaView className="flex-1 bg-slate-50"><ScrollView className="px-5" contentContainerStyle={{ paddingBottom: 100 }}><Text className="text-2xl font-bold text-slate-900 mt-5">My Gigs</Text><Text className="text-sm text-slate-500 mt-1 mb-5">Track every application and active project.</Text>{applications.map((app) => <TouchableOpacity key={app.id} onPress={() => app.status === 'active' || app.status === 'selected' ? navigation.navigate('WorkTracker', { applicationId: app.id }) : null} className="bg-white rounded-2xl p-4 mb-3 border border-slate-100"><View className="flex-row justify-between"><View className="flex-1 mr-2"><Text className="font-bold text-slate-900">{app.gigTitle}</Text><Text className="text-xs text-slate-500 mt-1">{app.businessName} · ₹{app.budget.toLocaleString('en-IN')}</Text></View><StatusPill status={app.status} label={app.status === 'active' && workState === 'submitted' ? 'In review' : undefined} /></View>{app.status === 'active' && <View className="h-2 bg-slate-100 rounded-full mt-4"><View className="h-2 bg-blue-600 rounded-full" style={{ width: `${app.progress || 20}%` }} /></View>}</TouchableOpacity>)}</ScrollView></SafeAreaView>;
};

export const GigDetailsScreen = ({ route }: any) => { const navigation = useNavigation<any>(); const { gigs, savedGigIds, toggleSaved } = useDemo(); const gig = gigs.find((item) => item.id === route.params.gigId) || gigs[0]; return <Screen title="Gig Details"><ScrollView className="px-5" contentContainerStyle={{ paddingBottom: 32 }}><View className="mt-5 bg-white rounded-2xl p-5 border border-slate-100"><View className="flex-row justify-between"><View className="flex-1"><Text className="text-xl font-bold text-slate-900">{gig.title}</Text><Text className="text-sm text-slate-500 mt-1">{gig.businessName} · {gig.location}</Text></View><StatusPill status="open" /></View><View className="flex-row mt-4"><View className="bg-emerald-50 px-3 py-2 rounded-full mr-2"><Text className="text-emerald-700 text-xs font-bold">{gig.matchPercentage || 88}% skill match</Text></View><View className="bg-blue-50 px-3 py-2 rounded-full"><Text className="text-blue-600 text-xs font-bold">Verified business</Text></View></View><Text className="text-3xl font-bold text-slate-900 mt-6">₹{gig.budget.toLocaleString('en-IN')}</Text><Text className="text-sm text-slate-500">{gig.duration} · Deadline {gig.deadline}</Text><Text className="font-bold text-slate-900 mt-6">About this gig</Text><Text className="text-sm text-slate-600 leading-6 mt-2">{gig.description}</Text><Text className="font-bold text-slate-900 mt-6 mb-2">Deliverables</Text>{gig.deliverables.map((item) => <Text key={item} className="text-sm text-slate-600 mb-2">• {item}</Text>)}</View><View className="mt-4 flex-row"><TouchableOpacity onPress={() => toggleSaved(gig.id)} className="mr-3 px-5 justify-center rounded-full border border-slate-200"><Text className="font-semibold text-slate-700">{savedGigIds.includes(gig.id) ? 'Saved' : 'Save'}</Text></TouchableOpacity><View className="flex-1"><Cta label="Apply for this gig" onPress={() => navigation.navigate('ApplyGig', { gigId: gig.id })} /></View></View></ScrollView></Screen> };

export const ApplyGigScreen = ({ route }: any) => { const navigation = require('@react-navigation/native').useNavigation<any>(); const { gigs, applications, apply } = useDemo(); const gig = gigs.find((item) => item.id === route.params.gigId) || gigs[0]; const applied = applications.some((item) => item.gigId === gig.id); if (applied) return <Screen title="Application"><SuccessState title="Application submitted" subtitle="Your verified profile and skill match have been shared with the business." primaryLabel="View My Gigs" onPrimary={() => navigation.navigate('MyGigs')} /></Screen>; return <Screen title="Apply"><ScrollView className="px-5 pt-5"><View className="bg-blue-50 rounded-2xl p-4"><Text className="font-bold text-slate-900">{gig.title}</Text><Text className="text-sm text-slate-600 mt-1">₹{gig.budget.toLocaleString('en-IN')} · {gig.businessName}</Text></View><Text className="font-bold text-slate-900 mt-6">Why are you a good fit?</Text><TextInput multiline defaultValue="My verified skills and past work are a strong match for this project. I can start right away and will keep you updated throughout." className="bg-white border border-slate-200 rounded-xl p-4 h-32 mt-3 text-slate-800" textAlignVertical="top"/><View className="mt-6"><Cta label="Submit application" onPress={() => { apply(gig); }} /></View></ScrollView></Screen> };

const workSteps = (state: string) => [{ id: '1', label: 'Selected', status: 'done' as const }, { id: '2', label: 'Working', status: state === 'active' ? 'current' as const : 'done' as const }, { id: '3', label: 'Review', status: state === 'submitted' || state === 'revision' ? 'current' as const : state === 'paid' ? 'done' as const : 'pending' as const }, { id: '4', label: 'Paid', status: state === 'paid' ? 'done' as const : 'pending' as const }];
export const WorkTrackerScreen = ({ route }: any) => { const navigation = require('@react-navigation/native').useNavigation<any>(); const { applications, workStateByGig } = useDemo(); const application = applications.find((item) => item.id === route.params.applicationId) || applications[0]; const workState = workStateByGig[application.gigId] || 'active'; return <Screen title="Work Tracker"><ScrollView className="px-5 pt-5"><View className="bg-white rounded-2xl p-5"><Text className="text-lg font-bold text-slate-900">{application.gigTitle}</Text><Text className="text-sm text-slate-500 mt-1">{application.businessName} · ₹{application.budget.toLocaleString('en-IN')} protected payment</Text><View className="mt-7"><MilestoneStepper steps={workSteps(workState)} variant="horizontal" /></View></View><View className="bg-emerald-50 rounded-2xl p-4 mt-4 flex-row"><ShieldCheck color="#10B981"/><Text className="flex-1 ml-3 text-sm text-emerald-800">Payment is released only after the business approves your final deliverable.</Text></View>{workState === 'revision' && <View className="bg-red-50 rounded-2xl p-4 mt-4"><Text className="font-bold text-red-700">Revision requested</Text><Text className="text-sm text-red-700 mt-1">Please adjust the colour contrast and re-submit your final files.</Text></View>}{workState === 'paid' ? <View className="mt-6"><Cta label="Rate your experience" onPress={() => navigation.navigate('RateExperience', { gigId: application.gigId })} /></View> : <View className="mt-6"><Cta label={workState === 'submitted' ? 'Deliverable is under review' : 'Submit deliverable'} onPress={() => workState !== 'submitted' && navigation.navigate('SubmitWork', { applicationId: application.id })} /></View>}</ScrollView></Screen> };
export const SubmitWorkScreen = ({ route }: any) => { const navigation = require('@react-navigation/native').useNavigation<any>(); const { submitWork, applications } = useDemo(); const application = applications.find((item) => item.id === route.params.applicationId) || applications[0]; return <Screen title="Submit Deliverable"><ScrollView className="px-5 pt-5"><Text className="text-lg font-bold text-slate-900">Ready for review?</Text><Text className="text-sm text-slate-500 mt-1">Add a note and submit your files for the business to review.</Text><View className="bg-white rounded-2xl p-5 mt-5 border border-dashed border-blue-300 items-center"><FileCheck2 size={30} color="#2563EB"/><Text className="font-semibold text-slate-900 mt-3">Content pack_final.zip</Text><Text className="text-xs text-slate-500 mt-1">12 social templates · 8.2 MB</Text></View><TextInput multiline placeholder="Add a handover note" className="bg-white border border-slate-200 rounded-xl p-4 h-28 mt-4" textAlignVertical="top"/><View className="mt-6"><Cta label="Submit for review" onPress={() => { submitWork(application.gigId); navigation.replace('WorkTracker', { applicationId: application.id }); }} /></View></ScrollView></Screen> };
export const RevisionRequestedScreen = WorkTrackerScreen;
export const EarningsScreen = () => <Screen title="Earnings"><View className="p-5"><View className="bg-blue-600 rounded-2xl p-5"><Text className="text-blue-100">Total earnings</Text><Text className="text-3xl font-bold text-white mt-2">₹42,850</Text><Text className="text-blue-100 text-sm mt-1">₹3,200 pending approval</Text></View></View></Screen>;
export const NotificationsScreen = () => <Screen title="Notifications"><View className="p-5"><Text className="font-bold text-slate-900">Application shortlisted</Text><Text className="text-slate-500 mt-1">Aman's Gourmet Cafe shortlisted your profile.</Text></View></Screen>;
export const SavedGigsScreen = () => { const navigation = require('@react-navigation/native').useNavigation<any>(); const { gigs, savedGigIds } = useDemo(); return <Screen title="Saved Gigs"><ScrollView className="px-5 pt-4">{gigs.filter((gig) => savedGigIds.includes(gig.id)).map((gig) => <GigCard key={gig.id} gig={gig} onPress={() => navigation.navigate('GigDetails', { gigId: gig.id })} />)}</ScrollView></Screen> };
export const ReviewsScreen = () => <Screen title="Reviews"><View className="p-5 bg-white mx-5 mt-5 rounded-2xl"><Text className="font-bold text-slate-900">4.9 ★ · 24 completed gigs</Text><Text className="text-slate-600 mt-3">“Reliable, thoughtful and delivered ahead of schedule.”</Text><Text className="text-xs text-slate-500 mt-2">Modern Bites Cafe · Verified MSME</Text></View></Screen>;
export const StudentProfileScreen = () => { const navigation = require('@react-navigation/native').useNavigation<any>(); return <SafeAreaView className="flex-1 bg-slate-50"><ScrollView className="px-5"><Text className="text-2xl font-bold text-slate-900 mt-5">Profile</Text><View className="bg-white rounded-2xl p-5 mt-4"><Text className="text-xl font-bold text-slate-900">{studentUser.name} <Text className="text-blue-600">✓</Text></Text><Text className="text-sm text-slate-500 mt-1">{studentUser.college} · {studentUser.location}</Text><Text className="text-sm text-slate-600 mt-4">{studentUser.skills.join(' · ')}</Text></View>{[['Earnings','Earnings'],['Saved gigs','SavedGigs'],['Ratings & reviews','StudentReviews'],['Notifications','StudentNotifications']].map(([label, route]) => <TouchableOpacity key={route} onPress={() => navigation.navigate(route)} className="bg-white rounded-xl p-4 mt-3"><Text className="font-semibold text-slate-800">{label}</Text></TouchableOpacity>)}</ScrollView></SafeAreaView> };
export const MessagesListScreen = () => { const navigation = useNavigation<any>(); const { role } = useDemo(); return <SafeAreaView className="flex-1 bg-slate-50"><View className="p-5"><Text className="text-2xl font-bold text-slate-900">Messages</Text><TouchableOpacity onPress={() => navigation.navigate(role === 'business' ? 'BusinessChatThread' : 'ChatThread', { threadId: 'THREAD-001' })} className="bg-white rounded-2xl p-4 mt-5 border border-slate-100"><Text className="font-bold text-slate-900">Modern Bites Cafe ✓</Text><Text className="text-sm text-slate-500 mt-1">The concept sketches look amazing!</Text></TouchableOpacity></View></SafeAreaView> };
export const ChatThreadScreen = () => <Screen title="Modern Bites Cafe"><View className="p-5"><View className="bg-slate-100 self-start rounded-2xl p-3"><Text>The concept sketches look amazing!</Text></View><View className="bg-blue-600 self-end rounded-2xl p-3 mt-3"><Text className="text-white">Thank you! I’ll send the final pack shortly.</Text></View></View></Screen>;
export const RateExperienceScreen = () => <Screen title="Rate Experience"><View className="p-5"><Text className="text-lg font-bold text-slate-900">How was it working with Modern Bites Cafe?</Text><View className="flex-row mt-5">{[1,2,3,4,5].map((i) => <Star key={i} fill="#F59E0B" color="#F59E0B" size={34} />)}</View><View className="mt-6"><Cta label="Submit rating" onPress={() => Alert.alert('Thanks!', 'Your rating has been saved locally for this demo.')} /></View></View></Screen>;
export const GlobalSearchScreen = () => { const navigation = useNavigation<any>(); const { gigs } = useDemo(); const [query, setQuery] = useState(''); const results = gigs.filter((gig) => `${gig.title} ${gig.businessName} ${gig.skills.join(' ')}`.toLowerCase().includes(query.toLowerCase())); return <Screen title="Search"><ScrollView className="p-5"><View className="bg-white rounded-xl border border-slate-200 p-3 flex-row"><Search color="#64748B"/><TextInput value={query} onChangeText={setQuery} placeholder="Search gigs, skills or businesses" placeholderTextColor="#94A3B8" className="ml-2 flex-1"/></View>{query.length > 0 && results.map((gig) => <GigCard key={gig.id} gig={gig} onPress={() => navigation.navigate('GigDetails', { gigId: gig.id })} showBookmark={false} />)}{query.length > 0 && results.length === 0 && <Text className="text-center text-slate-500 mt-8">No verified gigs match that search.</Text>}</ScrollView></Screen> };

export const BusinessDashboardScreen = () => { const navigation = require('@react-navigation/native').useNavigation<any>(); return <SafeAreaView className="flex-1 bg-slate-50"><ScrollView className="px-5"><Text className="text-2xl font-bold text-slate-900 mt-5">Good evening, {businessUser.name.split(' ')[0]}</Text><Text className="text-sm text-slate-500 mt-1">Your verified business workspace</Text><View className="flex-row mt-5"><View className="flex-1 bg-white rounded-2xl p-4 mr-2"><Text className="text-2xl font-bold">3</Text><Text className="text-xs text-slate-500">Active gigs</Text></View><View className="flex-1 bg-white rounded-2xl p-4"><Text className="text-2xl font-bold">24</Text><Text className="text-xs text-slate-500">Applicants</Text></View></View><TouchableOpacity onPress={() => navigation.navigate('ManageApplicants', { gigId: 'GIG-001' })} className="bg-white rounded-2xl p-5 mt-4"><Text className="font-bold text-slate-900">Create Instagram Content Pack</Text><Text className="text-sm text-slate-500 mt-1">4 verified applicants · Review candidates →</Text></TouchableOpacity></ScrollView></SafeAreaView> };
export const BusinessProfileScreen = () => { const navigation = require('@react-navigation/native').useNavigation<any>(); return <SafeAreaView className="flex-1 bg-slate-50"><ScrollView className="px-5"><Text className="text-2xl font-bold text-slate-900 mt-5">Business Profile</Text><View className="bg-white rounded-2xl p-5 mt-4"><Text className="text-xl font-bold">{businessUser.businessName} <Text className="text-blue-600">✓</Text></Text><Text className="text-sm text-slate-500 mt-1">{businessUser.category} · {businessUser.location}</Text><Text className="text-sm text-slate-600 mt-4">Verified MSME · Member since {businessUser.memberSince}</Text></View>{[['Saved talent','SavedTalent'],['Notifications','BusinessNotifications'],['Support','ReportSupport']].map(([label, route]) => <TouchableOpacity key={route} onPress={() => navigation.navigate(route)} className="bg-white rounded-xl p-4 mt-3"><Text className="font-semibold text-slate-800">{label}</Text></TouchableOpacity>)}</ScrollView></SafeAreaView> };
export const ManageGigsScreen = () => { const navigation = require('@react-navigation/native').useNavigation<any>(); const { gigs } = useDemo(); return <SafeAreaView className="flex-1 bg-slate-50"><ScrollView className="px-5"><Text className="text-2xl font-bold text-slate-900 mt-5">Manage Gigs</Text>{gigs.slice(0,4).map((gig) => <TouchableOpacity onPress={() => navigation.navigate('ManageApplicants', { gigId: gig.id })} key={gig.id} className="bg-white rounded-2xl p-4 mt-3"><Text className="font-bold">{gig.title}</Text><Text className="text-sm text-slate-500 mt-1">{gig.applicantCount} applicants · ₹{gig.budget.toLocaleString('en-IN')}</Text></TouchableOpacity>)}</ScrollView></SafeAreaView> };
export const PostGigScreen = () => { const { postGig } = useDemo(); const [title, setTitle] = useState(''); const [budget, setBudget] = useState(''); return <SafeAreaView className="flex-1 bg-slate-50"><ScrollView className="px-5"><Text className="text-2xl font-bold text-slate-900 mt-5">Post a gig</Text><TextInput placeholder="Gig title" value={title} onChangeText={setTitle} className="bg-white rounded-xl p-4 mt-5 border border-slate-200"/><TextInput placeholder="Budget in ₹" value={budget} onChangeText={setBudget} keyboardType="numeric" className="bg-white rounded-xl p-4 mt-3 border border-slate-200"/><View className="mt-5"><Cta label="Publish gig" onPress={() => { const newGig: Gig = { id: `GIG-${Date.now()}`, title: title || 'Social media design support', businessId: 'BIZ-001', businessName: businessUser.businessName, businessInitials: businessUser.initials, businessAvatarColor: businessUser.avatarColor, isBusinessVerified: true, category: 'Design & Creative', description: 'A short local micro-gig for a verified student.', skills: ['Graphic Design'], budget: Number(budget) || 2500, duration: '3 days', deadline: 'This week', location: businessUser.location, distance: '2 km', workType: 'both', status: 'open', applicantCount: 0, rating: 4.8, reviewCount: 12, deliverables: ['Final deliverable'], postedDate: 'Just now' }; postGig(newGig); Alert.alert('Gig published', 'Your gig is now visible to matched, verified students.'); }} /></View></ScrollView></SafeAreaView> };
export const ManageApplicantsScreen = ({ route }: any) => { const navigation = require('@react-navigation/native').useNavigation<any>(); return <Screen title="Applicants"><ScrollView className="px-5 pt-4"><View className="bg-emerald-50 rounded-xl p-3 mb-3"><Text className="text-emerald-800 text-sm">All candidates are verified students with visible work history.</Text></View>{mockCandidates.map((candidate) => <CandidateCard key={candidate.id} candidate={candidate} onPress={() => navigation.navigate('CandidateProfile', { candidateId: candidate.id })} onShortlist={() => Alert.alert('Shortlisted', `${candidate.name} is now on your shortlist.`)} onMessage={() => navigation.navigate('BusinessChatThread', { threadId: 'THREAD-001' })} onSelect={() => navigation.navigate('ConfirmSelection', { candidateId: candidate.id, gigId: route.params.gigId })} />)}</ScrollView></Screen> };
export const CandidateProfileScreen = ({ route }: any) => { const navigation = require('@react-navigation/native').useNavigation<any>(); const candidate = mockCandidates.find((item) => item.id === route.params.candidateId) || mockCandidates[0]; return <Screen title="Candidate Profile"><ScrollView className="px-5 pt-5"><View className="bg-white rounded-2xl p-5"><Text className="text-xl font-bold">{candidate.name} <Text className="text-blue-600">✓</Text></Text><Text className="text-sm text-slate-500">{candidate.college} · {candidate.distance} away</Text><Text className="text-sm text-slate-600 mt-4">{candidate.skills.join(' · ')}</Text><Text className="font-bold mt-4">{candidate.rating} ★ · {candidate.gigsCompleted} completed gigs</Text></View><View className="mt-5"><Cta label="Select for this gig" onPress={() => navigation.navigate('ConfirmSelection', { candidateId: candidate.id, gigId: 'GIG-001' })} /></View></ScrollView></Screen> };
export const CandidateComparisonScreen = ManageApplicantsScreen;
export const ConfirmSelectionScreen = ({ route }: any) => { const navigation = require('@react-navigation/native').useNavigation<any>(); const { selectStudent } = useDemo(); const candidate = mockCandidates.find((item) => item.id === route.params.candidateId) || mockCandidates[0]; return <Screen title="Confirm selection"><View className="p-5"><View className="bg-white rounded-2xl p-5"><UserCheck color="#10B981" size={30}/><Text className="text-xl font-bold mt-4">Select {candidate.name}?</Text><Text className="text-sm text-slate-500 mt-2">They’ll be notified and the protected-payment work tracker will begin.</Text></View><View className="mt-5"><Cta label="Confirm & start work" onPress={() => { selectStudent(route.params.gigId); navigation.replace('BusinessWorkTracker', { gigId: route.params.gigId }); }} /></View></View></Screen> };
export const BusinessWorkTrackerScreen = ({ route }: any) => { const navigation = require('@react-navigation/native').useNavigation<any>(); const { gigs, workStateByGig, requestRevision, approveAndPay } = useDemo(); const gig = gigs.find((item) => item.id === route.params.gigId) || gigs[0]; const workState = workStateByGig[gig.id] || 'active'; return <Screen title="Work Tracker"><ScrollView className="px-5 pt-5"><View className="bg-white rounded-2xl p-5"><Text className="text-lg font-bold">{gig.title}</Text><Text className="text-sm text-slate-500 mt-1">Sandesh Reddy · verified student</Text><View className="mt-6"><MilestoneStepper steps={workSteps(workState)} variant="horizontal" /></View></View>{workState === 'submitted' ? <View className="mt-5"><Text className="font-bold text-slate-900 mb-3">Deliverable ready for review</Text><Cta label="Approve & release payment" onPress={() => { approveAndPay(gig.id); navigation.navigate('PaymentDetails', { transactionId: 'TXN-NEW' }); }} /><View className="mt-3"><Cta secondary label="Request revision" onPress={() => requestRevision(gig.id)} /></View></View> : <View className="bg-blue-50 rounded-2xl p-4 mt-5"><Text className="text-blue-800">{workState === 'paid' ? 'Payment released. You can now rate the experience.' : 'Waiting for the student’s deliverable.'}</Text></View>}</ScrollView></Screen> };
export const PaymentDetailsScreen = () => <Screen title="Payment Details"><View className="p-5"><View className="bg-emerald-50 rounded-2xl p-5"><CheckCircle2 color="#10B981" size={32}/><Text className="text-xl font-bold text-emerald-900 mt-3">Payment released</Text><Text className="text-sm text-emerald-800 mt-1">₹2,500 has been marked paid to the student in this local demo.</Text></View></View></Screen>;
export const BusinessNotificationsScreen = NotificationsScreen; export const SavedTalentScreen = () => <Screen title="Saved Talent"><ScrollView className="p-5">{mockCandidates.slice(0,2).map((candidate) => <CandidateCard key={candidate.id} candidate={candidate} showActions={false} />)}</ScrollView></Screen>; export const ReportSupportScreen = () => <Screen title="Support"><View className="p-5"><Text className="text-slate-600">Need help? Report an issue or contact YuvaConnect support.</Text></View></Screen>;
