import bcrypt from 'bcryptjs';
import { connectDatabase, disconnectDatabase } from './config/database.js';
import { Application, Conversation, Deliverable, Engagement, Gig, Message, Notification, Review, Transaction, User } from './models/index.js';

async function seed() {
  await connectDatabase();
  const passwordHash = await bcrypt.hash('Demo@123', 12);
  await Promise.all([Application.deleteMany({}), Deliverable.deleteMany({}), Engagement.deleteMany({}), Gig.deleteMany({}), Message.deleteMany({}), Conversation.deleteMany({}), Notification.deleteMany({}), Review.deleteMany({}), Transaction.deleteMany({}), User.deleteMany({})]);
  const [sandesh, arjun, priya, cafe, fashion, agency, bakery, fitness] = await User.create([
    { name: 'Sandesh Reddy', email: 'student@yuvaconnect.demo', passwordHash, role: 'student', isVerified: true, verificationStatus: 'verified', college: 'IIT Bombay', course: 'B.Tech Computer Science', year: '3rd Year', skills: ['Graphic Design', 'Social Media', 'Video Editing', 'React'], availability: ['weekends', 'evenings'], location: { city: 'Mumbai', locality: 'Powai' }, rating: 4.8, reviewCount: 2, completedGigs: 2, earnings: 7800 },
    { name: 'Arjun Mehta', email: 'arjun@yuvaconnect.demo', passwordHash, role: 'student', isVerified: true, verificationStatus: 'verified', college: 'NMIMS', course: 'BBA', year: '2nd Year', skills: ['Photography', 'Content Writing', 'Excel'], availability: ['weekends'], location: { city: 'Mumbai', locality: 'Vile Parle' }, rating: 4.6, completedGigs: 1 },
    { name: 'Priya Sharma', email: 'priya@yuvaconnect.demo', passwordHash, role: 'student', isVerified: true, verificationStatus: 'verified', college: 'Mumbai University', course: 'B.Des', year: '4th Year', skills: ['Graphic Design', 'UI Design', 'Illustration'], availability: ['evenings'], location: { city: 'Mumbai', locality: 'Andheri East' }, rating: 4.9, completedGigs: 4 },
    { name: 'Rohan Shah', email: 'business@yuvaconnect.demo', passwordHash, role: 'business', isVerified: true, verificationStatus: 'verified', businessName: 'Local Café', businessCategory: 'Food & Beverage', businessDescription: 'Neighbourhood café in Powai', businessAddress: 'Powai, Mumbai', location: { city: 'Mumbai', locality: 'Powai' } },
    { name: 'Meera Kapoor', email: 'fashion@yuvaconnect.demo', passwordHash, role: 'business', isVerified: true, verificationStatus: 'verified', businessName: 'Andheri Fashion Store', businessCategory: 'Retail', location: { city: 'Mumbai', locality: 'Andheri East' } },
    { name: 'Kunal Verma', email: 'agency@yuvaconnect.demo', passwordHash, role: 'business', isVerified: true, verificationStatus: 'verified', businessName: 'Digital Marketing Agency', businessCategory: 'Marketing', location: { city: 'Mumbai', locality: 'Vile Parle' } },
    { name: 'Neha Joshi', email: 'bakery@yuvaconnect.demo', passwordHash, role: 'business', isVerified: true, verificationStatus: 'verified', businessName: 'Local Bakery', businessCategory: 'Food & Beverage', location: { city: 'Mumbai', locality: 'Powai' } },
    { name: 'Vikram Singh', email: 'fitness@yuvaconnect.demo', passwordHash, role: 'business', isVerified: true, verificationStatus: 'verified', businessName: 'Fitness Studio', businessCategory: 'Fitness', location: { city: 'Mumbai', locality: 'Andheri East' } },
  ]);
  const base = { status: 'active', workType: 'both', duration: '3–5 days', deadline: new Date('2026-09-15') };
  const gigs = await Gig.create([
    { ...base, businessId: cafe.id, title: 'Instagram Content Pack', description: 'Create a month of vibrant Instagram posts and stories for our café.', category: 'Design', requiredSkills: ['Graphic Design', 'Social Media'], budget: 4500, location: { city: 'Mumbai', locality: 'Powai' }, deliverables: ['12 feed posts', '8 story templates'] },
    { ...base, businessId: fashion.id, title: 'Product Photography', description: 'Photograph new fashion arrivals for our online catalogue.', category: 'Photography', requiredSkills: ['Photography'], budget: 6000, location: { city: 'Mumbai', locality: 'Andheri East' }, deliverables: ['30 edited product photos'] },
    { ...base, businessId: agency.id, title: 'Website Landing Page', description: 'Design and build a focused landing page for a local brand.', category: 'Development', requiredSkills: ['React', 'UI Design'], budget: 9000, workType: 'remote', location: { city: 'Mumbai', locality: 'Vile Parle' }, deliverables: ['Responsive landing page'] },
    { ...base, businessId: bakery.id, title: 'Video Editing', description: 'Edit short vertical recipe and behind-the-scenes videos.', category: 'Video', requiredSkills: ['Video Editing'], budget: 3500, location: { city: 'Mumbai', locality: 'Powai' }, deliverables: ['5 short videos'] },
    { ...base, businessId: fitness.id, title: 'Bookkeeping', description: 'Organise monthly invoices and expense records.', category: 'Finance', requiredSkills: ['Excel'], budget: 5000, location: { city: 'Mumbai', locality: 'Andheri East' }, deliverables: ['Monthly workbook'] },
    { ...base, businessId: agency.id, title: 'Social Media Campaign', description: 'Plan content ideas and campaign reporting for a launch.', category: 'Marketing', requiredSkills: ['Social Media', 'Content Writing'], budget: 7000, location: { city: 'Mumbai', locality: 'Vile Parle' }, deliverables: ['Campaign plan', 'Report'] },
    { ...base, businessId: fashion.id, title: 'Poster Design', description: 'Create an eye-catching in-store promotional poster.', category: 'Design', requiredSkills: ['Graphic Design', 'Illustration'], budget: 2500, location: { city: 'Mumbai', locality: 'Andheri East' }, deliverables: ['Print-ready poster'] },
  ]);
  const app = await Application.create({ gigId: gigs[0].id, studentId: sandesh.id, proposal: 'I have designed high-performing visual content for local brands and can start this week.', availability: 'Evenings and weekends', status: 'selected' }); await Gig.findByIdAndUpdate(gigs[0].id, { status: 'assigned', selectedStudentId: sandesh.id, applicationCount: 2 });
  await Application.create({ gigId: gigs[0].id, studentId: priya.id, proposal: 'I can create a cohesive visual system for the café.', status: 'shortlisted' });
  const engagement = await Engagement.create({ gigId: gigs[0].id, businessId: cafe.id, studentId: sandesh.id, status: 'work_started', startedAt: new Date(), deadline: gigs[0].deadline, milestones: [{ label: 'Assigned', status: 'done', completedAt: new Date() }, { label: 'Work Started', status: 'done', completedAt: new Date() }, { label: 'Submitted for Review' }, { label: 'Approved' }, { label: 'Paid' }] });
  await Deliverable.create({ engagementId: engagement.id, submittedBy: sandesh.id, version: 1, message: 'Initial content directions and templates.', links: ['https://example.com/demo-deliverable'], status: 'under_review' });
  const completed = await Engagement.create({ gigId: gigs[1].id, businessId: fashion.id, studentId: sandesh.id, status: 'paid', startedAt: new Date('2026-07-15'), completedAt: new Date('2026-07-20'), milestones: [{ label: 'Assigned', status: 'done' }, { label: 'Work Started', status: 'done' }, { label: 'Submitted for Review', status: 'done' }, { label: 'Approved', status: 'done' }, { label: 'Paid', status: 'done' }] });
  await Gig.findByIdAndUpdate(gigs[1].id, { status: 'completed', selectedStudentId: sandesh.id });
  await Transaction.create({ gigId: gigs[1].id, engagementId: completed.id, businessId: fashion.id, studentId: sandesh.id, amount: 6000, platformFee: 300, gst: 54, total: 6354, status: 'released', transactionId: 'YC-DEMO-001' });
  await Review.create({ gigId: gigs[1].id, engagementId: completed.id, reviewerId: fashion.id, revieweeId: sandesh.id, rating: 5, tags: ['Professional', 'On Time'], comment: 'Excellent work and communication.' });
  const conversation = await Conversation.create({ participants: [sandesh.id, cafe.id], gigId: gigs[0].id, engagementId: engagement.id, lastMessageAt: new Date() }); await Message.create({ conversationId: conversation.id, senderId: cafe.id, text: 'Looking forward to seeing the first designs!' });
  await Notification.create([{ userId: sandesh.id, type: 'selection', title: 'You were selected!', message: 'Local Café selected you for Instagram Content Pack.', relatedId: engagement.id }, { userId: cafe.id, type: 'application', title: 'New application', message: 'Priya Sharma applied to your gig.', relatedId: gigs[0].id }]);
  console.info('Seed complete. Demo credentials: student@yuvaconnect.demo / Demo@123 and business@yuvaconnect.demo / Demo@123');
}
seed().then(disconnectDatabase).catch(async (error) => { console.error(error); await disconnectDatabase(); process.exit(1); });
