import { Router } from 'express';
import bcrypt from 'bcryptjs';
import { z } from 'zod';
import { authenticateUser, requireRole, type AuthRequest } from '../middleware/auth.middleware.js';
import { Application, Conversation, Deliverable, Engagement, Gig, Message, Notification, Review, SavedGig, SavedTalent, SupportTicket, Transaction, User } from '../models/index.js';
import { fail, ok } from '../utils/api.js';
import { signToken } from '../utils/jwt.js';
import { notify } from '../services/notification.service.js';
import { matchScore } from '../services/matching.service.js';

const router = Router(); const asyncRoute = (fn: any) => (req: any, res: any, next: any) => Promise.resolve(fn(req, res, next)).catch(next);
const parse = (schema: z.ZodTypeAny, body: unknown, res: any): any => { const r = schema.safeParse(body); if (!r.success) { fail(res, 400, 'Invalid request', r.error.issues); return null; } return r.data; };
const authBody = z.object({ name: z.string().min(2).optional(), email: z.string().email(), password: z.string().min(8), role: z.enum(['student', 'business']).optional(), phone: z.string().optional(), businessName: z.string().optional(), businessCategory: z.string().optional() });
const publicUser = (user: any) => user.toJSON ? user.toJSON() : user;

router.get('/health', (_req, res) => ok(res, { message: 'YuvaConnect API is running', database: 'connected' }));
router.post('/auth/register', asyncRoute(async (req, res) => { const input = parse(authBody.required({ name: true, role: true }), req.body, res); if (!input) return; if (await User.exists({ email: input.email })) return fail(res, 409, 'An account with this email already exists'); const user = await User.create({ ...input, passwordHash: await bcrypt.hash(input.password, 12), verificationStatus: 'pending' }); const token = signToken(user.id); ok(res, { token, user: publicUser(user) }, 201); }));
router.post('/auth/login', asyncRoute(async (req, res) => { const input = parse(authBody.pick({ email: true, password: true }), req.body, res); if (!input) return; const user = await User.findOne({ email: input.email }).select('+passwordHash'); if (!user || !(await bcrypt.compare(input.password, user.passwordHash))) return fail(res, 401, 'Invalid email or password'); const token = signToken(user.id); ok(res, { token, user: publicUser(user) }); }));
router.get('/auth/me', authenticateUser, asyncRoute(async (req: AuthRequest, res) => ok(res, { user: publicUser(await User.findById(req.user!.id)) })));
router.patch('/auth/profile', authenticateUser, asyncRoute(async (req: AuthRequest, res) => { const allowed = ['name', 'phone', 'profilePhoto', 'location', 'skills', 'availability', 'preferredWorkRadius', 'college', 'course', 'year', 'studentId', 'businessName', 'businessCategory', 'businessDescription', 'businessAddress']; const update = Object.fromEntries(Object.entries(req.body).filter(([k]) => allowed.includes(k))); const user = await User.findByIdAndUpdate(req.user!.id, update, { new: true, runValidators: true }); ok(res, { user: publicUser(user) }); }));

router.get('/gigs', asyncRoute(async (req: AuthRequest, res) => { const q: any = { status: 'active' }; const query = req.query as Record<string, string>; if (query.search) q.$or = [{ title: new RegExp(query.search, 'i') }, { description: new RegExp(query.search, 'i') }]; if (query.category) q.category = query.category; if (query.skills) q.requiredSkills = { $in: query.skills.split(',').map((x) => new RegExp(`^${x}$`, 'i')) }; if (query.workType) q.workType = query.workType; if (query.city) q['location.city'] = new RegExp(`^${query.city}$`, 'i'); if (query.locality) q['location.locality'] = new RegExp(`^${query.locality}$`, 'i'); if (query.minBudget || query.maxBudget) q.budget = { ...(query.minBudget ? { $gte: Number(query.minBudget) } : {}), ...(query.maxBudget ? { $lte: Number(query.maxBudget) } : {}) }; const page = Math.max(1, Number(query.page ?? 1)); const limit = Math.min(50, Math.max(1, Number(query.limit ?? 20))); const [gigs, total] = await Promise.all([Gig.find(q).populate('businessId', 'name businessName isVerified rating').sort(query.sort === 'budget_asc' ? { budget: 1 } : { createdAt: -1 }).skip((page - 1) * limit).limit(limit), Gig.countDocuments(q)]); const student = req.user?.role === 'student' ? await User.findById(req.user.id) : null; ok(res, { data: gigs.map((gig: any) => ({ ...gig.toJSON(), matchScore: student ? matchScore(student, gig) : undefined })), pagination: { page, limit, total, pages: Math.ceil(total / limit) } }); }));
router.get('/gigs/:id', asyncRoute(async (req: AuthRequest, res) => { const gig: any = await Gig.findById(req.params.id).populate('businessId', 'name businessName isVerified rating'); if (!gig) return fail(res, 404, 'Gig not found'); const student = req.user?.role === 'student' ? await User.findById(req.user.id) : null; ok(res, { gig: { ...gig.toJSON(), matchScore: student ? matchScore(student, gig) : undefined } }); }));
router.post('/gigs', authenticateUser, requireRole('business'), asyncRoute(async (req: AuthRequest, res) => { const input = parse(z.object({ title: z.string().min(3), description: z.string().min(10), category: z.string(), requiredSkills: z.array(z.string()).default([]), budget: z.number().positive(), duration: z.string().optional(), workType: z.enum(['remote', 'on-site', 'both']).default('both'), location: z.object({ city: z.string().optional(), locality: z.string().optional(), latitude: z.number().optional(), longitude: z.number().optional() }).optional(), deadline: z.coerce.date().optional(), deliverables: z.array(z.string()).default([]) }), req.body, res); if (!input) return; const gig = await Gig.create({ ...input, businessId: req.user!.id }); ok(res, { gig }, 201); }));
router.patch('/gigs/:id', authenticateUser, requireRole('business'), asyncRoute(async (req: AuthRequest, res) => { const gig = await Gig.findOneAndUpdate({ _id: req.params.id, businessId: req.user!.id }, req.body, { new: true, runValidators: true }); if (!gig) return fail(res, 404, 'Gig not found'); ok(res, { gig }); }));
router.delete('/gigs/:id', authenticateUser, requireRole('business'), asyncRoute(async (req: AuthRequest, res) => { const gig = await Gig.findOneAndDelete({ _id: req.params.id, businessId: req.user!.id }); if (!gig) return fail(res, 404, 'Gig not found'); ok(res, { message: 'Gig deleted' }); }));
for (const [path, status] of [['publish', 'active'], ['pause', 'paused'], ['close', 'cancelled']] as const) router.post(`/gigs/:id/${path}`, authenticateUser, requireRole('business'), asyncRoute(async (req: AuthRequest, res) => { const gig = await Gig.findOneAndUpdate({ _id: req.params.id, businessId: req.user!.id }, { status }, { new: true }); if (!gig) return fail(res, 404, 'Gig not found'); ok(res, { gig }); }));
router.get('/business/gigs', authenticateUser, requireRole('business'), asyncRoute(async (req: AuthRequest, res) => ok(res, { gigs: await Gig.find({ businessId: req.user!.id }).sort({ createdAt: -1 }) })));

router.post('/gigs/:gigId/apply', authenticateUser, requireRole('student'), asyncRoute(async (req: AuthRequest, res) => { const gig = await Gig.findOne({ _id: req.params.gigId, status: 'active' }); if (!gig) return fail(res, 404, 'Active gig not found'); const input = parse(z.object({ proposal: z.string().min(10), experience: z.string().optional(), availability: z.string().optional(), estimatedCompletionTime: z.string().optional(), portfolioLinks: z.array(z.string().url()).default([]) }), req.body, res); if (!input) return; try { const application = await Application.create({ ...input, gigId: gig.id, studentId: req.user!.id }); await Gig.findByIdAndUpdate(gig.id, { $inc: { applicationCount: 1 } }); await notify(gig.businessId.toString(), 'application', 'New application', 'A verified student applied to your gig.', application.id); ok(res, { application }, 201); } catch (e: any) { if (e.code === 11000) return fail(res, 409, 'You already applied to this gig'); throw e; } }));
router.get('/student/applications', authenticateUser, requireRole('student'), asyncRoute(async (req: AuthRequest, res) => ok(res, { applications: await Application.find({ studentId: req.user!.id }).populate({ path: 'gigId', populate: { path: 'businessId', select: 'name businessName isVerified' } }).sort({ createdAt: -1 }) })));
router.get('/applications/:id', authenticateUser, asyncRoute(async (req: AuthRequest, res) => { const app: any = await Application.findById(req.params.id).populate('gigId'); if (!app) return fail(res, 404, 'Application not found'); if (app.studentId.toString() !== req.user!.id && app.gigId.businessId.toString() !== req.user!.id) return fail(res, 403, 'Not allowed'); ok(res, { application: app }); }));
router.patch('/applications/:id/withdraw', authenticateUser, requireRole('student'), asyncRoute(async (req: AuthRequest, res) => { const app = await Application.findOneAndUpdate({ _id: req.params.id, studentId: req.user!.id, status: { $in: ['pending', 'shortlisted'] } }, { status: 'withdrawn' }, { new: true }); if (!app) return fail(res, 404, 'Application not found or cannot be withdrawn'); ok(res, { application: app }); }));
router.get('/gigs/:gigId/applications', authenticateUser, requireRole('business'), asyncRoute(async (req: AuthRequest, res) => { const gig = await Gig.findOne({ _id: req.params.gigId, businessId: req.user!.id }); if (!gig) return fail(res, 404, 'Gig not found'); ok(res, { applications: await Application.find({ gigId: gig.id }).populate('studentId', '-passwordHash') }); }));
for (const [path, status, title] of [['shortlist', 'shortlisted', 'You were shortlisted'], ['reject', 'rejected', 'Application update']] as const) router.patch(`/applications/:id/${path}`, authenticateUser, requireRole('business'), asyncRoute(async (req: AuthRequest, res) => { const app: any = await Application.findById(req.params.id).populate('gigId'); if (!app || app.gigId.businessId.toString() !== req.user!.id) return fail(res, 404, 'Application not found'); app.status = status; await app.save(); await notify(app.studentId.toString(), status === 'shortlisted' ? 'shortlist' : 'application', title, `Your application has been ${status}.`, app.id); ok(res, { application: app }); }));
router.patch('/applications/:id/select', authenticateUser, requireRole('business'), asyncRoute(async (req: AuthRequest, res) => { const app: any = await Application.findById(req.params.id).populate('gigId'); if (!app || app.gigId.businessId.toString() !== req.user!.id) return fail(res, 404, 'Application not found'); if (app.gigId.status !== 'active') return fail(res, 400, 'Gig is no longer accepting a selection'); app.status = 'selected'; await app.save(); await Application.updateMany({ gigId: app.gigId.id, _id: { $ne: app.id }, status: { $in: ['pending', 'shortlisted'] } }, { status: 'rejected' }); const gig = await Gig.findByIdAndUpdate(app.gigId.id, { selectedStudentId: app.studentId, status: 'assigned' }, { new: true }); const engagement = await Engagement.create({ gigId: gig!.id, businessId: req.user!.id, studentId: app.studentId, deadline: gig!.deadline, milestones: [{ label: 'Assigned', status: 'done', completedAt: new Date() }, { label: 'Work Started' }, { label: 'Submitted for Review' }, { label: 'Approved' }, { label: 'Paid' }] }); await notify(app.studentId.toString(), 'selection', 'You were selected!', `You have been selected for ${gig!.title}.`, engagement.id); ok(res, { application: app, engagement }); }));

const engagementFor = async (id: string, req: AuthRequest) => { const engagement: any = await Engagement.findById(id); return engagement && (engagement.studentId.toString() === req.user!.id || engagement.businessId.toString() === req.user!.id) ? engagement : null; };
router.get('/engagements/:id', authenticateUser, asyncRoute(async (req: AuthRequest, res) => { const engagement = await engagementFor(String(req.params.id), req); if (!engagement) return fail(res, 404, 'Engagement not found'); ok(res, { engagement }); }));
router.get('/student/engagements', authenticateUser, requireRole('student'), asyncRoute(async (req: AuthRequest, res) => ok(res, { engagements: await Engagement.find({ studentId: req.user!.id }).populate('gigId businessId', 'title budget businessName name').sort({ updatedAt: -1 }) })));
router.get('/business/engagements', authenticateUser, requireRole('business'), asyncRoute(async (req: AuthRequest, res) => ok(res, { engagements: await Engagement.find({ businessId: req.user!.id }).populate('gigId studentId', 'title budget name college').sort({ updatedAt: -1 }) })));
router.post('/engagements/:id/start', authenticateUser, requireRole('student'), asyncRoute(async (req: AuthRequest, res) => { const e: any = await Engagement.findOneAndUpdate({ _id: req.params.id, studentId: req.user!.id, status: { $in: ['assigned', 'revision_requested'] } }, { status: 'work_started', startedAt: new Date(), currentMilestone: 'Work Started', 'milestones.1.status': 'done', 'milestones.1.completedAt': new Date() }, { new: true }); if (!e) return fail(res, 404, 'Engagement not found or cannot be started'); await Gig.findByIdAndUpdate(e.gigId, { status: 'in_progress' }); await notify(e.businessId.toString(), 'work_update', 'Work started', 'The student started work on your gig.', e.id); ok(res, { engagement: e }); }));
router.post('/engagements/:id/submit', authenticateUser, requireRole('student'), asyncRoute(async (req: AuthRequest, res) => { const e: any = await Engagement.findOneAndUpdate({ _id: req.params.id, studentId: req.user!.id, status: { $in: ['work_started', 'revision_requested'] } }, { status: 'submitted', submittedAt: new Date(), currentMilestone: 'Submitted for Review', 'milestones.2.status': 'done', 'milestones.2.completedAt': new Date() }, { new: true }); if (!e) return fail(res, 404, 'Engagement not found or cannot be submitted'); await Gig.findByIdAndUpdate(e.gigId, { status: 'submitted' }); await notify(e.businessId.toString(), 'deliverable', 'Work submitted', 'A deliverable is ready for your review.', e.id); ok(res, { engagement: e }); }));
router.post('/engagements/:id/request-revision', authenticateUser, requireRole('business'), asyncRoute(async (req: AuthRequest, res) => { const e: any = await Engagement.findOneAndUpdate({ _id: req.params.id, businessId: req.user!.id, status: { $in: ['submitted', 'under_review'] } }, { status: 'revision_requested' }, { new: true }); if (!e) return fail(res, 404, 'Engagement not found or not ready for revision'); await notify(e.studentId.toString(), 'work_update', 'Revision requested', req.body.feedback || 'Please review the feedback and resubmit.', e.id); ok(res, { engagement: e }); }));
router.post('/engagements/:id/approve', authenticateUser, requireRole('business'), asyncRoute(async (req: AuthRequest, res) => { const e: any = await Engagement.findOneAndUpdate({ _id: req.params.id, businessId: req.user!.id, status: { $in: ['submitted', 'under_review'] } }, { status: 'approved', currentMilestone: 'Approved', 'milestones.3.status': 'done', 'milestones.3.completedAt': new Date() }, { new: true }); if (!e) return fail(res, 404, 'Engagement not found or not ready for approval'); const gig: any = await Gig.findById(e.gigId); const fee = Math.round(gig.budget * .05 * 100) / 100, gst = Math.round(fee * .18 * 100) / 100; const transaction = await Transaction.findOneAndUpdate({ engagementId: e.id }, { gigId: gig.id, engagementId: e.id, businessId: e.businessId, studentId: e.studentId, amount: gig.budget, platformFee: fee, gst, total: gig.budget + fee + gst, status: 'released', transactionId: `YC-${Date.now()}` }, { upsert: true, new: true }); e.status = 'paid'; e.completedAt = new Date(); e.currentMilestone = 'Paid'; e.milestones[4].status = 'done'; e.milestones[4].completedAt = new Date(); await e.save(); await Gig.findByIdAndUpdate(gig.id, { status: 'completed' }); await Application.updateOne({ gigId: gig.id, studentId: e.studentId }, { status: 'completed' }); await User.findByIdAndUpdate(e.studentId, { $inc: { completedGigs: 1, earnings: gig.budget } }); await notify(e.studentId.toString(), 'payment', 'Payment released', `₹${gig.budget} has been released for ${gig.title}.`, transaction.id); ok(res, { engagement: e, transaction }); }));
router.post('/engagements/:id/deliverables', authenticateUser, requireRole('student'), asyncRoute(async (req: AuthRequest, res) => { const e = await Engagement.findOne({ _id: req.params.id, studentId: req.user!.id }); if (!e) return fail(res, 404, 'Engagement not found'); const input = parse(z.object({ message: z.string().optional(), links: z.array(z.string().url()).default([]), files: z.array(z.any()).default([]) }), req.body, res); if (!input) return; const latest = await Deliverable.findOne({ engagementId: e.id }).sort({ version: -1 }); const deliverable = await Deliverable.create({ ...input, engagementId: e.id, submittedBy: req.user!.id, version: (latest?.version ?? 0) + 1 }); ok(res, { deliverable }, 201); }));
router.get('/engagements/:id/deliverables', authenticateUser, asyncRoute(async (req: AuthRequest, res) => { const e = await engagementFor(String(req.params.id), req); if (!e) return fail(res, 404, 'Engagement not found'); ok(res, { deliverables: await Deliverable.find({ engagementId: e.id }).sort({ version: -1 }) }); }));
for (const [path, status, engagementStatus] of [['request-revision', 'revision_requested', 'revision_requested'], ['approve', 'approved', 'approved']] as const) router.post(`/deliverables/:id/${path}`, authenticateUser, requireRole('business'), asyncRoute(async (req: AuthRequest, res) => { const d: any = await Deliverable.findById(req.params.id); const e: any = d && await Engagement.findOne({ _id: d.engagementId, businessId: req.user!.id }); if (!d || !e) return fail(res, 404, 'Deliverable not found'); d.status = status; d.feedback = req.body.feedback; await d.save(); e.status = engagementStatus; await e.save(); await notify(e.studentId.toString(), 'deliverable', status === 'approved' ? 'Deliverable approved' : 'Revision requested', d.feedback || 'Your deliverable status changed.', d.id); ok(res, { deliverable: d, engagement: e }); }));

router.post('/reviews', authenticateUser, asyncRoute(async (req: AuthRequest, res) => { const input = parse(z.object({ engagementId: z.string(), rating: z.number().int().min(1).max(5), tags: z.array(z.string()).default([]), comment: z.string().max(1000).optional() }), req.body, res); if (!input) return; const e: any = await engagementFor(input.engagementId, req); if (!e || !['approved', 'completed', 'paid'].includes(e.status)) return fail(res, 400, 'Only completed engagements can be reviewed'); const revieweeId = e.studentId.toString() === req.user!.id ? e.businessId : e.studentId; try { const review = await Review.create({ ...input, gigId: e.gigId, reviewerId: req.user!.id, revieweeId }); const stats = await Review.aggregate([{ $match: { revieweeId: review.revieweeId } }, { $group: { _id: '$revieweeId', rating: { $avg: '$rating' }, reviewCount: { $sum: 1 } } }]); await User.findByIdAndUpdate(revieweeId, { rating: Math.round(stats[0].rating * 10) / 10, reviewCount: stats[0].reviewCount }); await notify(revieweeId.toString(), 'rating', 'New rating received', 'You received a review for completed work.', review.id); ok(res, { review }, 201); } catch (err: any) { if (err.code === 11000) return fail(res, 409, 'You already reviewed this engagement'); throw err; } }));
router.get('/users/:id/reviews', asyncRoute(async (req, res) => ok(res, { reviews: await Review.find({ revieweeId: req.params.id }).populate('reviewerId', 'name businessName role isVerified').sort({ createdAt: -1 }) })));
router.get('/student/portfolio', authenticateUser, requireRole('student'), asyncRoute(async (req: AuthRequest, res) => { const engagements = await Engagement.find({ studentId: req.user!.id, status: { $in: ['completed', 'paid'] } }).populate('gigId businessId', 'title category description budget businessName name'); ok(res, { portfolio: engagements }); }));

router.get('/transactions', authenticateUser, asyncRoute(async (req: AuthRequest, res) => { const filter = req.user!.role === 'student' ? { studentId: req.user!.id } : { businessId: req.user!.id }; ok(res, { transactions: await Transaction.find(filter).populate('gigId', 'title') }); }));
router.get('/notifications', authenticateUser, asyncRoute(async (req: AuthRequest, res) => ok(res, { notifications: await Notification.find({ userId: req.user!.id }).sort({ createdAt: -1 }).limit(100) })));
router.patch('/notifications/:id/read', authenticateUser, asyncRoute(async (req: AuthRequest, res) => { const notification = await Notification.findOneAndUpdate({ _id: req.params.id, userId: req.user!.id }, { read: true }, { new: true }); if (!notification) return fail(res, 404, 'Notification not found'); ok(res, { notification }); }));
router.patch('/notifications/read-all', authenticateUser, asyncRoute(async (req: AuthRequest, res) => { await Notification.updateMany({ userId: req.user!.id, read: false }, { read: true }); ok(res, { message: 'Notifications marked as read' }); }));
router.post('/gigs/:id/save', authenticateUser, requireRole('student'), asyncRoute(async (req: AuthRequest, res) => { if (!await Gig.exists({ _id: req.params.id })) return fail(res, 404, 'Gig not found'); try { ok(res, { savedGig: await SavedGig.create({ userId: req.user!.id, gigId: req.params.id }) }, 201); } catch (e: any) { if (e.code === 11000) return fail(res, 409, 'Gig already saved'); throw e; } }));
router.delete('/gigs/:id/save', authenticateUser, requireRole('student'), asyncRoute(async (req: AuthRequest, res) => { await SavedGig.deleteOne({ userId: req.user!.id, gigId: req.params.id }); ok(res, { message: 'Gig unsaved' }); }));
router.get('/student/saved-gigs', authenticateUser, requireRole('student'), asyncRoute(async (req: AuthRequest, res) => ok(res, { savedGigs: await SavedGig.find({ userId: req.user!.id }).populate({ path: 'gigId', populate: { path: 'businessId', select: 'name businessName isVerified' } }) })));
router.post('/students/:id/save', authenticateUser, requireRole('business'), asyncRoute(async (req: AuthRequest, res) => { const student = await User.findOne({ _id: req.params.id, role: 'student' }); if (!student) return fail(res, 404, 'Student not found'); try { ok(res, { savedTalent: await SavedTalent.create({ businessId: req.user!.id, studentId: student.id }) }, 201); } catch (e: any) { if (e.code === 11000) return fail(res, 409, 'Student already saved'); throw e; } }));
router.delete('/students/:id/save', authenticateUser, requireRole('business'), asyncRoute(async (req: AuthRequest, res) => { await SavedTalent.deleteOne({ businessId: req.user!.id, studentId: req.params.id }); ok(res, { message: 'Student removed from saved talent' }); }));
router.get('/business/saved-talent', authenticateUser, requireRole('business'), asyncRoute(async (req: AuthRequest, res) => ok(res, { savedTalent: await SavedTalent.find({ businessId: req.user!.id }).populate('studentId', '-passwordHash') })));
router.post('/verification/submit', authenticateUser, asyncRoute(async (req: AuthRequest, res) => { const user = await User.findByIdAndUpdate(req.user!.id, { verificationStatus: 'pending', verificationSubmittedAt: new Date() }, { new: true }); ok(res, { user }); }));
router.get('/verification/status', authenticateUser, asyncRoute(async (req: AuthRequest, res) => { const user = await User.findById(req.user!.id).select('verificationStatus verificationSubmittedAt isVerified'); ok(res, { verification: user }); }));
router.post('/support', authenticateUser, asyncRoute(async (req: AuthRequest, res) => { const input = parse(z.object({ category: z.enum(['report_user', 'payment_issue', 'verification', 'work_dispute', 'technical', 'other']), reason: z.string().optional(), description: z.string().min(5), attachments: z.array(z.any()).default([]) }), req.body, res); if (!input) return; ok(res, { ticket: await SupportTicket.create({ ...input, userId: req.user!.id }) }, 201); }));
router.get('/support/my-tickets', authenticateUser, asyncRoute(async (req: AuthRequest, res) => ok(res, { tickets: await SupportTicket.find({ userId: req.user!.id }).sort({ createdAt: -1 }) })));
router.get('/conversations', authenticateUser, asyncRoute(async (req: AuthRequest, res) => ok(res, { conversations: await Conversation.find({ participants: req.user!.id }).populate('participants', 'name businessName role profilePhoto isVerified').populate('gigId', 'title').sort({ lastMessageAt: -1 }) })));
router.get('/conversations/:id/messages', authenticateUser, asyncRoute(async (req: AuthRequest, res) => { const conversation = await Conversation.findOne({ _id: req.params.id, participants: req.user!.id }); if (!conversation) return fail(res, 404, 'Conversation not found'); await Message.updateMany({ conversationId: conversation.id, senderId: { $ne: req.user!.id } }, { read: true }); ok(res, { messages: await Message.find({ conversationId: conversation.id }).sort({ createdAt: 1 }) }); }));
router.post('/conversations/:id/messages', authenticateUser, asyncRoute(async (req: AuthRequest, res) => { const conversation: any = await Conversation.findOne({ _id: req.params.id, participants: req.user!.id }); if (!conversation) return fail(res, 404, 'Conversation not found'); const input = parse(z.object({ text: z.string().min(1).max(3000) }), req.body, res); if (!input) return; const message = await Message.create({ ...input, conversationId: conversation.id, senderId: req.user!.id }); conversation.lastMessageAt = new Date(); await conversation.save(); const recipient = conversation.participants.find((x: any) => x.toString() !== req.user!.id); if (recipient) await notify(recipient.toString(), 'message', 'New message', input.text.slice(0, 100), conversation.id); ok(res, { message }, 201); }));

export default router;
